version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/caddy"
      - "/fluentd"
      - "/grafana"
      - "/mysql"
      - "/notification"
      - "/visualization"
    schedule:
      interval: "monthly"
