version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/fluentd"
      - "/grafana"
      #- "/visualization"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
