dist: bionic
language: generic
sudo: required

branches:
  only:
    - master

service:
  - docker

cache:
  apt: true
  directories:
    - docker

install:
  - bash .travis/install_docker.sh
  - docker run --name buildkit -d --privileged -p 1234:1234 moby/buildkit:v0.6.0 --addr tcp://0.0.0.0:1234
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
  - BUILDKIT_HOST=tcp://0.0.0.0:1234 buildctl build --help
  - mv .secrets/rails_secret_key_base.txt.example .secrets/rails_secret_key_base.txt
  - mv .secrets/db_password.txt.example .secrets/db_password.txt
  - mv .secrets/accounts.yml.example .secrets/accounts.yml

jobs:
  include:
    - stage: "Test: building"
      name: "Building sindan-fluentd"
      script: bash .travis/test_building_fluentd.sh
    - name: "Building sindan-visualization (with build-time secret option)"
      script: bash .travis/test_building_visualization.sh

    - stage: "Test: initializing and running"
      name: "Initialize database and start rails app with fluentd"
      script:
        - ls -al docker
        - gzip -dc docker/fluentd.tar.gz | docker load
        - gzip -dc docker/visualization.tar.gz | docker load
        - bash .travis/test_initializing.sh
        - bash .travis/test_running.sh

    - stage: "Deploy:"
      name: "Deploy to DockerHub"
      install: false
      script:
        - ls -al docker
        - gzip -dc docker/fluentd.tar.gz | docker load
        - gzip -dc docker/visualization.tar.gz | docker load
        - bash .travis/deploy_dockerhub.sh
    # - name: "Deploy to GitHub Package Registry"
    #   install: false
    #   script:
    #     - ls -al docker
    #     - gzip -dc docker/fluentd.tar.gz | docker load
    #     - gzip -dc docker/visualization.tar.gz | docker load
    #     - bash .travis/deploy_github.sh

env:
  global:
    # DOCKER_HUB_USERNAME
    - secure: HRCELBzl6gBtVuRWlxnuzu6c+EGeyj6+8nicF+rysV2lpYtmsi7xn3CRHBoLYi1ryeBPh6AA08cxVyySpR5qXgXT1v5y3A2OWjggbYBWbVDwREE9PStIxf9WNU/AfvXA8tqdh9CR02PfT1lsnuCdEc3o8afE8WNqfPbbLcF85Uiy7CPRTneCNlSR60HEkO7P/1lI562FC6DatqDRiFM5yJ9WwVejoQ5+alaF54Bpxv4ZvVKZsNJW8Tj+r/7nBoGrI2F60xaSR7G2G2KWZ0W/SRGn/YO11p44QTvaLfrQcQTH/jv9uQyQ6+ZMDOG/R4kQXfTMu8ems6RwJPTQj41MJ99y2lvGVCO5L/apX+5jyJKz5YwFNANE7WFywWRa9rNGDhOqdtdrvBw31NKCXVBuXTvsdlSrSUGV6wYhpJVRWGQTAyVXR3y8zfWqp1W0oK58VlOxYe6COGrNRjLZUKaoHdMO1Bg0cY5PsZza2Rvj/L4o31BkubQK86fjYCC33ADc1g6b+9lI1N16aBahYzmuzfdT/WU6i2p3iMqaytK3sVh/4bikdQioGU4BZe8AYzizkJVTeRf5U3UFfotgFvoq8omINs47p8F+sacJ0M43Hmbvp6AflUSJhz31V7/uKYbponcQJVpjf/6tNlO6YNciAzKGMAxAR1QxwfKyMh+ckpA=

    # DOCKER_HUB_PASSWORD
    - secure: sAewE3bnLdeWSrB8UGIXL4qwZVUfn+pKpwaVpVjdwbruapHtp/XRPa/8HJAwZWeGIegUcr4DbJGPUejeKMgcuCLpyMfAoJmGQY2vDbd+YRIVeZ7XJXgoPzRhGqiHrEuEqLpnh0ZV09432yk/wb2spVhi1TUuBQHlc2flD6/u8dwbK/0H9XP5pb46uaqHwk3JBm4qKY/XAG3pZApgKshMAvz0alB7Wfj2QM/m44fV5sRo5rXqcTzcRS1pH8XdMZZtsmyK54HsGAJVRm1N/AdTES3njxa1Kq5pwBjnyIdXmUlKs43TRprrmDMxCWheIj2bIC6AvxRc3RHVKqzNT7+5FQWbQBgK2nIKW0G0JcO4LejrGWrno91nsfJuX2CcCaYldLETRyh5xpDQ938jO/Qy1LB1aetUbMck5pqt+bHByYFToLQIOchNmT9ZCK+IzjV0dt3Lmt+k4snOskvOdB3Q0TsmspRsc1BfFSg3nv0Ht/8dhJzCUkO7Yd2fk/ifxk79x7X6N+mjS+Fktgao/fTlyUMeu2+nohLaDmZtsie43XIUTk8iqzLU42oXh4dFt9zftvZ7MSQRpxjwmAtR6QmwU9Al1IQ8XE2NhLKVB7CkVttm9U7QigABO1EZEN6qAG6bPF07x0N0/1BQc70C0nudE0GyTv16UWQ4421gmmeITLM=

    # GITHUB_PKG_USERNAME
    - secure: FTbOnDYoNu3QCUUJXrMmFxPbwgbxKy3/dEy3hLby37IXHCSzMl8T5qETjT1zXudLuRo/Dl58g/Jb+359owTcSN2WZjCdsn1n97k+StBatB/FMEJmMW3Ylws5P6L56HQpS4SqrXxvGz/2AaJbGVXbChveAdrz2ff1pvaZ1m8RH7zIPXD0d6wiNT5E7FfhyFFpJyFvNBZg0Pyk2Y3IupDQmE0BmYjpq/PdsoK2vd7aUvXgI5thCYQMzWsacObjuaRXbS3pXOAFLyTCzoglyMNLeKBqwwnI1uYNO3aVlr0yq12HypH1HKNPjvqvXE70euBjRs6JZ8nrlOgSV6KvaEYdM1yP/xChp57EG3Xfgq7RUoU28GYf0GdPIJoLpx1ioav3ylm6nm4DCv4q6Q24VICIFdjuQIQ7ktIf9mIRsxzO4U8iHljrbxrNCwBOPteJxfd9BNW8SzuFscQD8Ca++2s4vmzTqaAxXIWq9nmBxyAKpHC2Sngl/FAJkBMKCdJTscgmDzRRw4LfNcuQ7mI+SBoqyGZWiaHbQFk0WItrNx+D03z3KFmhTeuIEATfybPLSnf2NLp7/+Yz9WT5Aw3+hfa7pV6KjDJ8OtV1xaWYM31tF2Fy9hAN4J6UCbMDqw8eqcMYQgnJ+jz9MtxZ4h122G+TG/ePiUSY2f/cNVDfmyZvCOI=

    # GITHUB_PKG_TOKEN
    - secure: GQoJuJ0ubQJLcVwutZALkR+damhYysauyq2W+qqZi0eka03mqyRUFcrvg47fh6KNARblJqTlY4sIgq0IqqFblRzkgG+xIPsWmGSyU0BTs4AeIKID9HmmvML9wd/bJ6BBTEa/wNO5LD+CdbIeeOgYOsOsMDqb0rikZvwMyRwCmBSESnlUYLzCMN0ideUoiTplrs54qRZwIbhFH93OtMmDFksbearDYxQV40Ay59xEU5Yax4+Cv+M47xchT4w2QFHEVYRRjLTspr1ENNSOa3LX9MHaGi3zFr75OOXfgeqopHhVCvwCvSlq1hlwFIzKfsgthVE6mMiQvow6dmwsW8ydeald+JWbDbQ7FAY2fZ+pOjZLWKmepJPORdrDqj1GOLmVNbarqrmEwkuNOb3voIeOCflctwHznvKKmOuIYFNpd7wnw9iIf2y72sUKA3/1Tp/BB4jceaj/jOn7tQet/P/y/RCQ1XtOx0rcCUVMXubExKoNOfVuBj8F4Wv/kDUdIyy2v08AKpXxnQDNharG0Mhw9J+z7OU7K/tmsJ5QPgcP0QLrzbtTcUgsjt2AKzDz7prCdyxOgZcvEZpwc8sJTmwY9Hx65FNWy+DXZ129SBplRkOCXmJKwCXg8EQBhbBVKdY7WcNEbHBOkG6GNRIjy4EJ/bPTksEgAsCPt0+DOGX5S38=
