x-healthcheck:
  &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: "30"
  start_period: "20s"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    env_file:
      - ./caddy/domain.env
    ports:
      - "13000:13000"
      - "13001:13001"
      - "18888:18888"
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  fluentd:
    image: ghcr.io/sindan/sindan-docker/fluentd:latest
    build:
      context: ./fluentd
    hostname: sindan-fluentd
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8888:8888"
    secrets:
      - db_password
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD_FILE: "/run/secrets/db_password"
    healthcheck:
      <<: *default-healthcheck
      test: wget --spider http://127.0.0.1:8080/ || exit 1
    logging: *default-logging
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - fluentd-data:/fluentd/log
    labels:
      com.sindan-net.sindan-fluentd.description: "Receive logs from sindan-clients and forward them to MySQL"

  mysql:
    image: mysql:8.0
    hostname: sindan-mysql
    restart: always
    expose:
      - "3306"
    secrets:
      - db_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_GRANTED_USER}
      MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
    healthcheck:
      <<: *default-healthcheck
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$(cat $$MYSQL_PASSWORD_FILE)
    logging: *default-logging
    volumes:
      - ./mysql/dump_database.sh:/dump_database.sh:ro
      - ./mysql/restore_database.sh:/restore_database.sh:ro
      - mysql-data:/var/lib/mysql
    labels:
      com.sindan-net.sindan-mysql.description: "Storing diagnosis logs for sindan-visualization"

  visualization: &visualization
    image: ghcr.io/sindan/sindan-docker/visualization:latest
    build:
      context: ./visualization
      target: production
      secrets:
        - rails_secret_key_base
        - db_password
      args:
        - BUILDTIME_RAILS_SECRETKEY_FILE=/run/secrets/rails_secret_key_base
        - BUILDTIME_DB_PASSWORD_FILE=/run/secrets/db_password
    hostname: sindan-visualization
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    secrets:
      - db_password
      - rails_secret_key_base
      - accounts
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD_FILE: "/run/secrets/db_password"
      RAILS_SECRETKEY_FILE: "/run/secrets/rails_secret_key_base"
      ACCOUNTS_FILE: "/run/secrets/accounts"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    healthcheck:
      <<: *default-healthcheck
      test: wget --spider http://127.0.0.1:3000/ || exit 1
      timeout: "2s"
    logging: *default-logging
    volumes:
      - visualization-data:/app
    labels:
      com.sindan-net.sindan-visualization.description: "Web frontend to manage diagnosis logs"

  visualization-noexpose:
    <<: *visualization
    ports: []

  grafana: &grafana
    image: ghcr.io/sindan/sindan-docker/grafana:latest
    build:
      context: ./grafana
    hostname: sindan-grafana
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3000"
    secrets:
      - db_password
      - gf_user
      - gf_password
    logging: *default-logging
    environment:
      GF_PATHS_CONFIG: "/etc/grafana/config.ini"
      GF_INSTALL_PLUGINS: "grafana-clock-panel"
      GF_SECURITY_ADMIN_USER__FILE: "/run/secrets/gf_user"
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/gf_password"
    healthcheck:
      <<: *default-healthcheck
      test: wget --spider http://127.0.0.1:3000/api/health || exit 1
      timeout: "2s"
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      com.sindan-net.sindan-grafana.description: "Grafana dashboard"

  grafana-noexpose:
    <<: *grafana
    ports: []

secrets:
  db_password:
    file: .secrets/db_password.txt
  rails_secret_key_base:
    file: .secrets/rails_secret_key_base.txt
  accounts:
    file: .secrets/accounts.yml
  gf_user:
    file: .secrets/gf_user.txt
  gf_password:
    file: .secrets/gf_password.txt

volumes:
  fluentd-data:
  mysql-data:
  visualization-data:
  grafana-data:
  caddy_data:
  caddy_config:
