version: '3.7'

x-healthcheck:
  &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: 3
  start_period: "20s"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  fluentd:
    image: sindan/fluentd:1.3.0
    build:
      context: ./fluentd
    hostname: sindan-fluentd
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "8888:8888"
    secrets:
      - db_password
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD_FILE: "/run/secrets/db_password"
    healthcheck:
      <<: *default-healthcheck
      test: wget --spider http://127.0.0.1:8080/ || exit 1
    logging: *default-logging
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - fluentd-data:/fluentd/log
    labels:
      com.sindan-net.description: "Receive logs from sindan-clients and forward them to MySQL"

  mysql:
    image: mysql:5.7
    hostname: sindan-mysql
    restart: always
    expose:
      - "3306"
    secrets:
      - db_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_GRANTED_USER}
      MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
    healthcheck:
      <<: *default-healthcheck
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$(cat /run/secrets/db_password)
    logging: *default-logging
    volumes:
      - mysql-data:/var/lib/mysql
    labels:
      com.sindan-net.description: "Storing diagnosis logs for sindan-visualization"

  visualization:
    image: sindan/visualization:1.3.1
    build:
      context: ./visualization
      target: production
    hostname: sindan-visualization
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    secrets:
      - db_password
      - rails_secret_key_base
      - accounts
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD_FILE: "/run/secrets/db_password"
      RAILS_SECRETKEY_FILE: "/run/secrets/rails_secret_key_base"
      ACCOUNTS_FILE: "/run/secrets/accounts"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    healthcheck:
      <<: *default-healthcheck
      test: wget --spider http://127.0.0.1:3000/ || exit 1
      timeout: "2s"
    logging: *default-logging
    volumes:
      - visualization-data:/app
    labels:
      com.sindan-net.description: "Web frontend to manage diagnosis logs"

secrets:
  db_password:
    file: .secrets/db_password.txt
  rails_secret_key_base:
    file: .secrets/rails_secret_key_base.txt
  accounts:
    file: .secrets/accounts.yml

volumes:
  fluentd-data:
  mysql-data:
  visualization-data:
