mysql:
  build: mysql
  environment:
   MYSQL_ROOT_PASSWORD: sindantest

fluentd:
  build: fluentd
  ports:
   - "24224:24224"
   - "8888:8888"
  environment:
    ENV: DEV

webui:
  build: webui
  ports:
   - "80:80"
   - "443:443"
  environment:
    ENV: DEV
