version: '3.7'

x-healthcheck:
  &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: 3
  start_period: "20s"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  fluentd:
    image: fluentd-sindan:v1.6-1
    build:
      context: ./fluentd
    restart: always
    expose:
      - "9900"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      << : *default-healthcheck
      test: curl -f http://127.0.0.1:9900 || exit 1
    logging: *default-logging
    volumes:
      - fluentd-data:/fluentd/log
    labels:
      com.sindan-net.description: "Receive logs from sindan-clients and forward them to MySQL"

  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    secrets:
      - db_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "sindan"
      MYSQL_DATABASE: "sindan_production"
      MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
    healthcheck:
      << : *default-healthcheck
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$(cat /run/secrets/db_password)
    logging: *default-logging
    volumes:
      - mysql-data:/var/lib/mysql
    labels:
      com.sindan-net.description: "Storing diagnosis logs for sindan-visualization"

secrets:
  db_password:
    file: .secrets/db_password.txt

volumes:
  fluentd-data:
  mysql-data:
