apiVersion: 1

datasources:
  - name: "sindan-mysql"
    type: mysql
    version: 1
    editable: false
    url: mysql:3306
    database: sindan_production
    user: sindan
    secureJsonData:
      password: ${GF_MYSQL_DB_PASSWORD}
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 5
      connMaxLifetime: 14400

