{
 "title": "SINDAN by fluentd.docker.local",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sindanClientID",
    "label": "node_id",
    "query": "SELECT distinct(mac_addr) FROM log_campaigns ORDER BY mac_addr;"
   },
   {
    "name": "target_v4rtt_srv",
    "label": "v4rtt_srv",
    "query": "www.yahoo.co.jp, www.wide.ad.jp"
   },
   {
    "name": "target_v6rtt_srv",
    "label": "v6rtt_srv",
    "query": "www.google.co.jp, www.wide.ad.jp"
   },
   { "name": "target_v4pmtu", "label": "v4pmtu", "query": "8.8.8.8, 203.178.139.60" },
   {
    "name": "target_v6pmtu",
    "label": "v6pmtu",
    "query": "2001:4860:4860::8888, 2001:200:0:180c::6"
   },
   {
    "name": "target_v4http_srv",
    "label": "v4http_srv",
    "query": "www.yahoo.co.jp, www.wide.ad.jp"
   },
   {
    "name": "target_v6http_srv",
    "label": "v6http_srv",
    "query": "www.google.co.jp, www.wide.ad.jp"
   }
  ]
 },
 "panels": [
  {
   "title": "v4rtt_srv of $target_v4rtt_srv",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_max\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_max\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_ave\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_min\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v6rtt_srv of $target_v6rtt_srv",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_max\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_max\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_ave\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_min\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v4dnsrtt of GPDNS4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_dual.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_ipv4.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_ipv6.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_dual.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_ipv4.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_ipv6.sindan-net.com\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v6dnsrtt of GPDNS6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_dual.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_ipv4.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_ipv6.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_dual.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_ipv4.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_ipv6.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "p4pmtu_srv",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS4(1.1.1.1)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"1.1.1.1\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS4(8.8.8.8)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"sh.wide.ad.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"203.178.139.60\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v6pmtu_srv",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS6(::1111)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2606:4700:4700::1111\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS6(::8888)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"sh.wide.ad.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2001:200:0:180c::6\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v4http_srv of $target_v4http_srv",
   "type": "graph",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0 as \"www.yahoo.co.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4http_srv\" and\n  target = \"$target_v4http_srv\""
    }
   ]
  },
  {
   "title": "v6http_srv of $target_v6http_srv",
   "type": "graph",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0 as \"www.google.co.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6http_srv\" and\n  target = \"$target_v6http_srv\""
    }
   ]
  },
  {
   "title": "WiFi Status",
   "type": "graph",
   "description": "SNR should be 20 or more for a data network.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"rssi\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"rssi\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"noise\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"noise\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  a.occurred_at AS \"time\",\n  (a.detail+0.0) - (b.detail+0.0) AS \"SNR\"\nFROM\n  (\n  SELECT log_campaign_uuid, occurred_at, detail\n  FROM diagnosis_logs\n  WHERE\n    $__timeFilter(occurred_at) AND\n    log_type = \"RSSI\" AND\n    log_campaign_uuid in (\n      SELECT log_campaign_uuid\n      FROM log_campaigns\n      WHERE mac_addr = \"$sindanClientID\"\n    )\n  ) AS a\nLEFT JOIN\n  (\n  SELECT log_campaign_uuid, occurred_at, detail\n  FROM diagnosis_logs\n  WHERE\n    $__timeFilter(occurred_at) AND\n    log_type = \"noise\" AND\n    log_campaign_uuid in (\n      SELECT log_campaign_uuid\n      FROM log_campaigns\n      WHERE mac_addr = \"$sindanClientID\"\n    )\n  ) As b\nON a.log_campaign_uuid = b.log_campaign_uuid"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"RSSI\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"rssi\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "Latest Campaign",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  mac_addr AS \"sindanClientID\"\nFROM log_campaigns\nWHERE\n  $__timeFilter(occurred_at)\nORDER BY occurred_at"
    }
   ]
  },
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 } }
 ]
}