{
 "title": "SINDAN new dashboard (written by Irikida)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "sindanClientID",
    "label": "node_id",
    "query": "SELECT distinct(mac_addr) FROM log_campaigns ORDER BY mac_addr;"
   },
   {
    "name": "target_v4rtt_srv",
    "label": "v4rtt_srv",
    "query": "1.1.1.1, 8.8.8.8, 203.178.139.60"
   },
   {
    "name": "target_v6rtt_srv",
    "label": "v6rtt_srv",
    "query": "www.google.co.jp, www.wide.ad.jp"
   },
   {
    "name": "target_v4pmtu",
    "label": "v4pmtu",
    "query": "1.1.1.1, 8.8.8.8, 203.178.139.60"
   },
   {
    "name": "target_v6pmtu",
    "label": "v6pmtu",
    "query": "2001:4860:4860::8888, 2001:200:0:180c::6"
   },
   {
    "name": "target_v4http_srv",
    "label": "v4http_srv",
    "query": "www.yahoo.co.jp, www.wide.ad.jp"
   },
   {
    "name": "target_v6http_srv",
    "label": "v6http_srv",
    "query": "www.google.co.jp, www.wide.ad.jp"
   }
  ]
 },
 "panels": [
  {
   "title": "Alert",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest Campaign",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  mac_addr AS \"sindanClientID\"\nFROM log_campaigns\nWHERE\n  $__timeFilter(occurred_at)\nORDER BY occurred_at DESC\nLIMIT 30;"
    }
   ]
  },
  { "title": "Application Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "v4speedtest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"Download speedtest\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4speedtest_download\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
    },
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"Upload speedtest\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4speedtest_upload\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v4speedtest_rtt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"v4speedtest_rtt\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4speedtest_rtt\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "v4http_srv of $target_v4http_srv",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0 as \"$target_v4http_srv\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4http_websrv\" and\n  target = \"$target_v4http_srv\" and\n  log_campaign_uuid IN (\n  SELECT\n    log_campaign_uuid\n  FROM log_campaigns\n  WHERE mac_addr = \"$sindanClientID\" )"
    }
   ]
  },
  {
   "title": "v4speedtest_jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"v4speedtest_jitter\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4speedtest_jitter\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "Global Network Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "v4alive_srv of $target_v4rtt_srv",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  CASE\r\n    WHEN detail LIKE '%0 packets received%' THEN 0  -- pingÇ™é∏îsÇµÇΩèÍçá\r\n    ELSE 1  -- pingÇ™ê¨å˜ÇµÇΩèÍçá\r\n  END AS \"v4alive_srv\"\r\nFROM diagnosis_logs\r\nWHERE\r\n  $__timeFilter(occurred_at) AND\r\n  log_type = \"v4alive_srv\" AND\r\n  target = \"$target_v4rtt_srv\" and\r\n  log_campaign_uuid IN (\r\n    SELECT\r\n      log_campaign_uuid\r\n    FROM log_campaigns\r\n    WHERE mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at DESC\r\n"
      }
     ]
    },
    {
     "title": "v4loss_srv of $target_v4rtt_srv",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"v4loss_srv\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4loss_srv\" and\r\n  target = \"$target_v4rtt_srv\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "p4pmtu_srv",
     "type": "stat",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS4(1.1.1.1)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"1.1.1.1\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS4(8.8.8.8)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"8.8.8.8\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"sh.wide.ad.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4pmtu_srv\" and\n  target = \"203.178.139.60\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v4rtt_srv of $target_v4rtt_srv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_max\"\nFROM diagnosis_logs\n\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_max\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_ave\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_srv_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_srv_min\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    }
   ]
  },
  {
   "title": "Name Resolution Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "v4dns_rtt of $target_v4rtt_srv",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_dual.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_ipv4.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_AAAA_ipv6.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_dual.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_ipv4.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4dnsrtt_A_ipv6.sindan-net.com\" and\n  target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Network Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "v4alive_router",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  CASE\r\n    WHEN detail LIKE '%0 packets received%' THEN 0  -- pingÇ™é∏îsÇµÇΩèÍçá\r\n    ELSE 1  -- pingÇ™ê¨å˜ÇµÇΩèÍçá\r\n  END AS \"v4alive_router\"\r\nFROM diagnosis_logs\r\nWHERE\r\n  $__timeFilter(occurred_at) AND\r\n  log_type = \"v4alive_router\" AND\r\n  log_campaign_uuid IN (\r\n    SELECT\r\n      log_campaign_uuid\r\n    FROM log_campaigns\r\n    WHERE mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at DESC\r\n"
      }
     ]
    },
    {
     "title": "v4loss_router",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"v4loss_router\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4loss_router\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v4alive_namesrv",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  CASE\r\n    WHEN detail LIKE '%0 packets received%' THEN 0  -- pingÇ™é∏îsÇµÇΩèÍçá\r\n    ELSE 1  -- pingÇ™ê¨å˜ÇµÇΩèÍçá\r\n  END AS \"v4alive_namesrvr\"\r\nFROM diagnosis_logs\r\nWHERE\r\n  $__timeFilter(occurred_at) AND\r\n  log_type = \"v4alive_namesrv\" AND\r\n  log_campaign_uuid IN (\r\n    SELECT\r\n      log_campaign_uuid\r\n    FROM log_campaigns\r\n    WHERE mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at DESC\r\n"
      }
     ]
    },
    {
     "title": "v4loss_namesrv",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"v4loss_namesrv\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v4loss_namesrv\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v4rtt_router",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_router_max\"\nFROM diagnosis_logs\n\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_router_max\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_router_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_router_ave\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_router_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_router_min\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v4rtt_namesrv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"\tv4rtt_namesrv_max\"\nFROM diagnosis_logs\n\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_namesrv_max\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_namesrv_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_namesrv_ave\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"v4rtt_namesrv_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v4rtt_namesrv_min\" and\n  #target = \"$target_v4rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    }
   ]
  },
  { "title": "Data Link Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "ifstatus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  CASE\r\n    WHEN detail LIKE '%0 packets received%' THEN 0  -- pingÇ™é∏îsÇµÇΩèÍçá\r\n    ELSE 1  -- pingÇ™ê¨å˜ÇµÇΩèÍçá\r\n  END AS \"ifstatus\"\r\nFROM diagnosis_logs\r\nWHERE\r\n  $__timeFilter(occurred_at) AND\r\n  log_type = \"ifstatus\" AND\r\n  log_campaign_uuid IN (\r\n    SELECT\r\n      log_campaign_uuid\r\n    FROM log_campaigns\r\n    WHERE mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at DESC"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"RSSI\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"rssi\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    }
   ]
  },
  {
   "title": "iftype",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail AS \"iftype\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) AND\n  log_type = \"iftype\" AND\n  log_campaign_uuid IN (\n    SELECT\n      log_campaign_uuid\n    FROM log_campaigns\n    WHERE mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "ssid",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail AS \"ssid\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) AND\n  log_type = \"ssid\" AND\n  log_campaign_uuid IN (\n    SELECT\n      log_campaign_uuid\n    FROM log_campaigns\n    WHERE mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "WiFi Status",
   "type": "timeseries",
   "description": "SNR should be 20 or more for a data network.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"rssi\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"rssi\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"noise\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"noise\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
    },
    {
     "rawSql": "SELECT\n  a.occurred_at AS \"time\",\n  (a.detail+0.0) - (b.detail+0.0) AS \"SNR\"\nFROM\n  (\n  SELECT log_campaign_uuid, occurred_at, detail\n  FROM diagnosis_logs\n  WHERE\n    $__timeFilter(occurred_at) AND\n    log_type = \"RSSI\" AND\n    log_campaign_uuid in (\n      SELECT log_campaign_uuid\n      FROM log_campaigns\n      WHERE mac_addr = \"$sindanClientID\"\n    )\n  ) AS a\nLEFT JOIN\n  (\n  SELECT log_campaign_uuid, occurred_at, detail\n  FROM diagnosis_logs\n  WHERE\n    $__timeFilter(occurred_at) AND\n    log_type = \"noise\" AND\n    log_campaign_uuid in (\n      SELECT log_campaign_uuid\n      FROM log_campaigns\n      WHERE mac_addr = \"$sindanClientID\"\n    )\n  ) As b\nON a.log_campaign_uuid = b.log_campaign_uuid"
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "v6speedtest_download",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"Download speedtest\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v6speedtest_download\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v6speedtest_upload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\r\n  occurred_at AS \"time\",\r\n  detail+0 as \"Upload speedtest\"\r\nFROM diagnosis_logs\r\n\r\nWHERE\r\n  $__timeFilter(occurred_at) and\r\n  log_type = \"v6speedtest_upload\" and\r\n  log_campaign_uuid in (\r\n    select\r\n      log_campaign_uuid\r\n    from log_campaigns\r\n    where mac_addr = \"$sindanClientID\" )\r\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v6dnsrtt of GPDNS6",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_dual.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_ipv4.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"AAAA_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_AAAA_ipv6.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_dual\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_dual.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv4\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_ipv4.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"A_ipv6\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6dnsrtt_A_ipv6.sindan-net.com\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v6pmtu_srv",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS6(::1111)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2606:4700:4700::1111\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"GPDNS6(::8888)\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2001:4860:4860::8888\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 as \"sh.wide.ad.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6pmtu_srv\" and\n  target = \"2001:200:0:180c::6\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v6rtt_srv of $target_v6rtt_srv",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_max\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_max\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_ave\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_ave\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      },
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0.0 AS \"v6rtt_srv_min\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6rtt_srv_min\" and\n  target = \"$target_v6rtt_srv\" and\n  log_campaign_uuid in (\n    select\n      log_campaign_uuid\n    from log_campaigns\n    where mac_addr = \"$sindanClientID\" )\nORDER BY occurred_at"
      }
     ]
    },
    {
     "title": "v6http_srv of $target_v6http_srv",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  occurred_at AS \"time\",\n  detail+0 as \"www.google.co.jp\"\nFROM diagnosis_logs\nWHERE\n  $__timeFilter(occurred_at) and\n  log_type = \"v6http_srv\" and\n  target = \"$target_v6http_srv\""
      }
     ]
    }
   ]
  }
 ]
}