default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: mysql
  port: 3306

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_GRANTED_USER'] %>
  password: <%= File.open(ENV['DB_PASSWORD_FILE']).read.chomp %>
