
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: mysql
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_GRANTED_USER'] %>
  password: <%= ENV['SINDAN_VISUALIZATION_DATABASE_PASSWORD'] %>
